### ISSUE TITLE
Problem with programatically accessing a service

### ISSUE THREAD

**Issue by phermsdorf** [ECF/tcpsocketdistributionprovider#2]
Hi,

i noticed a problem with service handling when the service is consumed programmatically.
I've tried to edit my little example to show the problem (https://github.com/phermsdorf/ecf-consumer-provider-example):
* deactivate ServiceConsumer (e.g. Comment the @Component Annotation)
* the SecondConsumer should periodically call the IHello service every 5 seconds

My observation is that it is once called, the service get's unregistred (because the references got to 0) and then the next call fails, which triggers the re-import mechanism to that the next call agains will work ...

Maybe you can have a look at it.

Thanks!

Bye Peter

**Comment by phermsdorf** [comment]
@scottslewis I'm on vacation for two weeks now, so you can rest a bit too ;)

**Comment by scottslewis** [comment]
I'm sorry that I missed you @phermsdorf ...this is the first chance I've had to look at this (my house is being painted this week along with plenty of other things).

But in any event, when I do as described (comment out ServiceConsumer component and allow the programmatic import of SecondConsumer to result in remote call to Service)...I get the service registrations (both client registration and server registration) staying available and the scheduled call of Hello is done repeatedly...this is from server impl side console):

![image](https://user-images.githubusercontent.com/159988/179373596-d019b47b-447a-4385-bef8-be759ef093d6.png)

Is there something else I should be doing to trigger what you are seeing?  (the premature unregistration of the service impl?...or client)?

Thanks...and please do have a good vacation.

Scott

**Comment by phermsdorf** [comment]
Hi @scottslewis, sorry for being late with my reply. I hope your house looks shiny and new now ;)

I've tried again and can produce the issue. On my side i see the errors in the consumer log (I've added one more output statement - you see it at Line 34 in the screenshot):
![image](https://user-images.githubusercontent.com/11061378/183423637-94405e76-cb85-40fe-b725-ad4e477ae8f0.png)

* first run succeeds (no "no service available")
* next run fails (triggers reimport)
* next run works again and so on

the complete error message in the log is:
```
!ENTRY org.eclipse.ecf.osgi.services.remoteserviceadmin 4 0 2022-08-08 14:55:48.036
!MESSAGE org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.osgi.services.remoteserviceadmin;code=4;message=org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin:postEvent:No EventAdmin service available to send eventTopic=org/osgi/service/remoteserviceadmin/IMPORT_REGISTRATION eventProperties={event=RemoteServiceAdminEvent[containerID=URIID [uri=tcp://localhost:3000], getType()=1, getSource()=org.eclipse.ecf.osgi.services.remoteserviceadmin_4.7.1.v20201102-0420 [24], getException()=null, getImportReference()=ImportReference[importEndpoint=null;exception=null], getExportReference()=null], bundle.id=24, objectClass=[Ljava.lang.String;@12d42a, timestamp=1659963348034, endpoint.id=tcp://localhost:3000, service.imported.configs=[Ljava.lang.String;@2d42f0, bundle.symbolicname=org.eclipse.ecf.osgi.services.remoteserviceadmin, import.registration=ECFEndpointDescription[{ecf.endpoint.id.ns=ecf.namespace.socket, ecf.endpoint.rsfilter=(&(ecf.robjectClass=service.IHello)), ecf.rsvc.id=0, endpoint.id=tcp://localhost:3000, endpoint.package.version.service=1.0.0, my.id=myservice, objectClass=[Ljava.lang.String;@1667186, osgi.async=intent, osgi.basic=intent, osgi.private=intent, remote.configs.supported=[Ljava.lang.String;@1f9cec6, remote.intents.supported=[Ljava.lang.String;@1fdf3f4, service.imported=org.eclipse.ecf.provider.tcpsocket.client.TCPSocketClientContainer$3@12dc4f1, service.imported.configs=[Ljava.lang.String;@12fde11}], bundle=org.eclipse.ecf.osgi.services.remoteserviceadmin_4.7.1.v20201102-0420 [24], bundle.version=4.7.1.v20201102-0420};severity4;exception=null;children=[]]

```
but maybe that is a kind of follow-up error ...

I think it somehow has to do with service reference counting: I get a breakpoint hit in org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin.ProxyServiceFactory.ungetService(Bundle, ServiceRegistration, Object) Line 1853 after the first successful call:
```
if (remoteProxyCount == 1L)
				containerAdapter.ungetRemoteService(rsReference); // this one is called

```
which (i think) triggers service unregistration.
The call stack is:
```
Thread [Worker-0: demo] (Suspended (breakpoint at line 1853 in RemoteServiceAdmin$ProxyServiceFactory))	
	owns: ServiceFactoryUse<S>  (id=229)	
	RemoteServiceAdmin$ProxyServiceFactory.ungetService(Bundle, ServiceRegistration, Object) line: 1853	
	ServiceFactoryUse$2.run() line: 265	
	ServiceFactoryUse$2.run() line: 1	
	AccessController.doPrivileged(PrivilegedAction<T>) line: not available [native method]	
	ServiceFactoryUse<S>.factoryUngetService(S) line: 262	
	ServiceFactoryUse<S>.ungetService() line: 163	
	ServiceConsumer$2.ungetService(ServiceUse<S>, S) line: 53	
	ServiceRegistrationImpl<S>.ungetService(BundleContextImpl, ServiceConsumer, S) line: 632	
	ServiceRegistry.ungetService(BundleContextImpl, ServiceReferenceImpl<?>) line: 612	
	BundleContextImpl.ungetService(ServiceReference<?>) line: 699	
	ServiceHandle<T>.close() line: 30	
	SecondConsumer.callService() line: 26	
	SecondConsumer.access$0(SecondConsumer) line: 17	
	SecondConsumer$1.run(IProgressMonitor) line: 35	
	Worker.run() line: 63	

```
So the ServiceHandle.close() gives back the service reference which leads to service unregistration. 
But from my understanding unused service references should be returned .... ?

Thank's  for looking at the problem.

Bye Peter

**Comment by scottslewis** [comment]
Hi Peter,
> Hi @scottslewis, sorry for being late with my reply. I hope your house looks shiny and new now ;)

Actually it does :-).   Very satisfying as we've owned the house for 25+ years and this is the first time we've painted it.  We liked the old color but it was getting...old...and we like the new colors even better.

> 
> I've tried again and can produce the issue. On my side i see the errors in the consumer log (I've added one more output statement - you see it at Line 34 in the screenshot): ![image](https://user-images.githubusercontent.com/11061378/183423637-94405e76-cb85-40fe-b725-ad4e477ae8f0.png)
> 
>     * first run succeeds (no "no service available")
> 
>     * next run fails (triggers reimport)
> 
>     * next run works again and so on
> 
> 
> the complete error message in the log is:
> 
> ```
> !ENTRY org.eclipse.ecf.osgi.services.remoteserviceadmin 4 0 2022-08-08 14:55:48.036
> !MESSAGE org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.osgi.services.remoteserviceadmin;code=4;message=org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin:postEvent:No EventAdmin service available to send eventTopic=org/osgi/service/remoteserviceadmin/IMPORT_REGISTRATION eventProperties={event=RemoteServiceAdminEvent[containerID=URIID [uri=tcp://localhost:3000], getType()=1, getSource()=org.eclipse.ecf.osgi.services.remoteserviceadmin_4.7.1.v20201102-0420 [24], getException()=null, getImportReference()=ImportReference[importEndpoint=null;exception=null], getExportReference()=null], bundle.id=24, objectClass=[Ljava.lang.String;@12d42a, timestamp=1659963348034, endpoint.id=tcp://localhost:3000, service.imported.configs=[Ljava.lang.String;@2d42f0, bundle.symbolicname=org.eclipse.ecf.osgi.services.remoteserviceadmin, import.registration=ECFEndpointDescription[{ecf.endpoint.id.ns=ecf.namespace.socket, ecf.endpoint.rsfilter=(&(ecf.robjectClass=service.IHello)), ecf.rsvc.id=0, endpoint.id=tcp://localhost:3000, endpoint.package.version.service=1.0.0, my.id=myservice, objectClass=[Ljava.lang.String;@1667186, osgi.async=intent, osgi.basic=intent, osgi.private=intent, remote.configs.supported=[Ljava.lang.String;@1f9cec6, remote.intents.supported=[Ljava.lang.String;@1fdf3f4, service.imported=org.eclipse.ecf.provider.tcpsocket.client.TCPSocketClientContainer$3@12dc4f1, service.imported.configs=[Ljava.lang.String;@12fde11}], bundle=org.eclipse.ecf.osgi.services.remoteserviceadmin_4.7.1.v20201102-0420 [24], bundle.version=4.7.1.v20201102-0420};severity4;exception=null;children=[]]
> ```
> 
> but maybe that is a kind of follow-up error ...

I'm pretty sure it's unrelated to what you describe below.  The above appears to me to be ECF RSA impl complaining that it can't find an EventAdmin impl in the runtime to post async events to (as RSA spec dictates).   If you want to make this go away, just include the following bundle in your runtime:  org.eclipse.equinox.event.  I don't think it's non-presence should have any side effects.  Please do let me know if it changes any of what you describe below.

> 
> I think it somehow has to do with service reference counting: I get a breakpoint hit in org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin.ProxyServiceFactory.ungetService(Bundle, ServiceRegistration, Object) Line 1853 after the first successful call:

I'm still not getting any failures at all...so not getting any ServiceHandle.close()/unget/unregistration at all.  So let me describe in detail what I'm doing and you tell me what's wrong:

Here are your instructions:

deactivate ServiceConsumer (e.g. Comment the https://github.com/component Annotation)
// I added a comment to the component annotation in ServiceConsumer class...e.g.
//@Component
public class ServiceConsumer {

This of course means that the component xml gets deleted, the entry in manifest gets removed, and the build.properties gets updated to remove the component xml...all by the ds annotation processing.

then I launch the service provider, and launch the service consumer.

    the SecondConsumer should periodically call the IHello service every 5 seconds

and it does...and in my runtimes it just keeps calling the IHello service forever (running for a while now).   

Here's the component list on the client:


rg.eclipse.core.runtime.content.IContentTypeManager in bundle 26 (org.eclipse.core.contenttype:3.8.100.v20210910-0640) enabled, 1 instance.
    Id: 0, State:ACTIVE
service.consumer.ServiceImporter in bundle 30 (service.consumer:1.0.0.qualifier) enabled, 1 instance.
    Id: 1, State:ACTIVE
osgi> 

As you can see the ServiceImporter is active, and I can see it print out Hello on the server/provider every 5 seconds.

>It my observation is that it is once called, the service get's unregistred (because the references >got to 0) and then the next call fails, which triggers the re-import mechanism to that the next >call agains will work ...

My question:   Is it supposed to fail somehow on the first call?  If so, why?


> Thread [Worker-0: demo] (Suspended (breakpoint at line 1853 in RemoteServiceAdmin$ProxyServiceFactory))	
> 	owns: ServiceFactoryUse<S>  (id=229)	
> 	RemoteServiceAdmin$ProxyServiceFactory.ungetService(Bundle, ServiceRegistration, Object) line: 1853	
> 	ServiceFactoryUse$2.run() line: 265	
> 	ServiceFactoryUse$2.run() line: 1	
> 	AccessController.doPrivileged(PrivilegedAction<T>) line: not available [native method]	
> 	ServiceFactoryUse<S>.factoryUngetService(S) line: 262	
> 	ServiceFactoryUse<S>.ungetService() line: 163	
> 	ServiceConsumer$2.ungetService(ServiceUse<S>, S) line: 53	
> 	ServiceRegistrationImpl<S>.ungetService(BundleContextImpl, ServiceConsumer, S) line: 632	
> 	ServiceRegistry.ungetService(BundleContextImpl, ServiceReferenceImpl<?>) line: 612	
> 	BundleContextImpl.ungetService(ServiceReference<?>) line: 699	
> 	ServiceHandle<T>.close() line: 30	
> 	SecondConsumer.callService() line: 26	
> 	SecondConsumer.access$0(SecondConsumer) line: 17	
> 	SecondConsumer$1.run(IProgressMonitor) line: 35	
> 	Worker.run() line: 63	
> ```
> 
> So the ServiceHandle.close() gives back the service reference which leads to service unregistration. But from my understanding unused service references should be returned .... ?

When I look at my copy of the source from your repo, Here's the SecondConsumer class:

`package service.consumer.programatically;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Status;
import org.eclipse.core.runtime.jobs.Job;
import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;

import service.IHello;

public class SecondConsumer {
	
	public SecondConsumer() {
	}

	private void callService() {
		//that would be done by a utility class - just for the example
		try( ServiceHandle<IHello> serviceHandle = new ServiceHandle<IHello>(getBundleContext(), IHello.class)) {
			IHello service = serviceHandle.getService();
			if(service==null) {
				System.err.println("no service available");
			}else {
				service.sayHello();
			}
		}
	}
	
	public void start() {
		Job job = new Job("demo") {
			@Override
			protected IStatus run(IProgressMonitor monitor) {
				try {
					callService();
				} finally {
					schedule(5000L);
				}
				return Status.OK_STATUS;
			}
		};
		//give the ServiceImporter some time tu run
		job.schedule(5000L);
	}

	private BundleContext getBundleContext() {
		return FrameworkUtil.getBundle(getClass()).getBundleContext();
	}

}`

When I look at your stack trace above, the line numbers don't line up as expected in the above file...e.g. line 26  in copy above appears to be the close bracket } for the try block.

Is it possible that you somehow have a copy different from what's checked into your repo?  I just pulled from the repo and everything is up to date on my end.

Thanks,

Scott

**Comment by phermsdorf** [comment]
Hi @scottslewis 

I added the suggested org.eclipse.equinox.event bundle to the launch configurations and pushed that with an additional debug output which was shown in the screenshot above:

While further investigation the issue I noticed that I was using "our" current target platform because i tried to integrate that provider in our product. 
Our current target is 2020-12. In the tcpsocketdistributionprovider repository you added a target definition called ecf-photon.target which actually points to a target 2022-03 (including current ECF version).

When using that target definition it works like you described.
When replacing the content of ecf-photon.target with

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="TCP Distribution Provider Target" sequenceNumber="43">
<locations>
<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
<unit id="org.eclipse.license.feature.group" version="1.0.1.v20140414-1359"/>
<repository location="http://download.eclipse.org/cbi/updates/license/1.0.1.v20140414-1359"/>
</location>
<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
<unit id="org.eclipse.pde.feature.group" version="0.0.0"/>
<unit id="org.eclipse.pde.source.feature.group" version="0.0.0"/>
<unit id="org.eclipse.platform.feature.group" version="0.0.0"/>
<unit id="org.eclipse.platform.source.feature.group" version="0.0.0"/>
<unit id="org.eclipse.ecf.remoteservice.sdk.feature.feature.group" version="0.0.0"/>
<unit id="org.eclipse.ecf.remoteservice.sdk.feature.source.feature.group" version="0.0.0"/>
<repository location="http://download.eclipse.org/releases/2020-12/"/>
</location>
</locations>
</target>
```
you should see the described problem.

As fixing things in old versions is not something one likes I'll investigate if an upgrade to a current target is possible.

Bye Peter

**Comment by phermsdorf** [comment]
Hi Scott (@scottslewis ),

it took  me a wile to update our target platform to 2022-06 but stick with Jetty 9.x (because we include Apache Camel which is still bound to Jetty 9.x) . 
My litte test client and server now work with the included ECF version.

While integration the tcpsocket distribution provider into our code base i now observe another issue:
not all of our remote service are "correctly exported".
Tracing output for one of the services in question:
```
(TRACE)[09/21/22;15:18:15:221]TRACING org.eclipse.ecf.osgi.services.remoteserviceadmin.TopologyManagerImpl#advertiseEndpointDescription(advertising endpointDescription=ECFEndpointDescription[{ecf.endpoint.id=ecftcp://peter-HP-ZBook-15v-G5:39829/server, ecf.endpoint.id.ns=org.eclipse.ecf.core.identity.StringID, ecf.endpoint.ts=1663766295216, ecf.rsvc.id=4, endpoint.framework.uuid=1153c9bb-3a35-47ba-b849-5350aa628158, endpoint.id=ac499d8f-87f4-4e8e-971a-14392cdfba11, endpoint.package.version.com.godyo.p4.workflow.api=1.0.0, endpoint.service.id=249, objectClass=[Ljava.lang.String;@32069394, remote.configs.supported=[Ljava.lang.String;@4edd8a0a, remote.intents.supported=[Ljava.lang.String;@14a049f9, service.imported=true, service.imported.configs=[Ljava.lang.String;@4edd8a0a, xxecf.generic.server.port=8889}] and IServiceInfo ServiceInfo[uri=ecfosgirsvc://127.0.1.1:32565/osgirsvc_SdCsnIVMzNL+x/t8FzuLd28hrTU=;id=ServiceID[type=ServiceTypeID[typeName=_ecfosgirsvc._default.default._iana];location=ecfosgirsvc://127.0.1.1:32565/osgirsvc_SdCsnIVMzNL+x/t8FzuLd28hrTU=;full=_ecfosgirsvc._default.default._iana@ecfosgirsvc://127.0.1.1:32565/osgirsvc_SdCsnIVMzNL+x/t8FzuLd28hrTU=];priority=0;weight=0;props=ServiceProperties[{xxecf.generic.server.port=8889, objectClass=com.godyo.p4.workflow.api.IWorkflowService, ecf.endpoint.id=ecftcp://peter-HP-ZBook-15v-G5:39829/server, endpoint.service.id=249, ecf.endpoint.ts=1663766295216, remote.configs.supported=ecf.generic.server, endpoint.package.version.com.godyo.p4.workflow.api=1.0.0, remote.intents.supported=osgi.basic osgi.async osgi.private passByValue exactlyOnce ordered, endpoint.id=ac499d8f-87f4-4e8e-971a-14392cdfba11, ecf.endpoint.id.ns=org.eclipse.ecf.core.identity.StringID, endpoint.framework.uuid=1153c9bb-3a35-47ba-b849-5350aa628158, service.imported.configs=ecf.generic.server, ecf.rsvc.id=4}]]) 
(TRACE)[09/21/22;15:18:15:227]TRACING org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin#exportService(exported registrations=[ExportRegistration[exportReference=ExportReference[exportEndpoint=ExportEndpoint[serviceReference={com.godyo.p4.workflow.api.IWorkflowService}={service.id=249, service.bundleid=59, service.scope=bundle, xxecf.generic.server.port=8889, component.name=com.godyo.p5.server.workflow.ActivitiWorkflowService, service.exported.interfaces=*, component.id=41};rsRegistration=RemoteServiceRegistrationImpl[remoteServiceID=org.eclipse.ecf.remoteservice.RemoteServiceID[containerID=StringID[ecftcp://peter-HP-ZBook-15v-G5:39829/server];containerRelativeID=4];rserviceranking=0;classes=[com.godyo.p4.workflow.api.IWorkflowService];state=0;properties={ordered=intent, osgi.private=intent, xxecf.generic.server.port=8889, osgi.basic=intent, exactlyOnce=intent, osgi.async=intent, ecf.rsvc.id=4, passByValue=intent}]];exception=null;];closed=false]]) 

```
this looks OK, but org.eclipse.ecf.remoteservice.RemoteServiceRegistryImpl.publishService is never called for this service and so the clients cannot use that service.
No idea what is different with this service than with the others. They all are defined like this:

```
@Component(property = {
		Constants.EXPORTED_INTERFACES,
		Constants.EXPORTED_CONFIGS,
		Constants.SERVER_PORT })
public class ActivitiWorkflowService implements IWorkflowService {

```
I need to debug that further.

Bye Peter

**Comment by phermsdorf** [comment]
@scottslewis i still could not figure out what the problem is. BTW: should i open a separate issue for this problem? 
(after upgrading to a more current ecf version the programatic service call now works as expected)
One observation was: the service in question (ActivitiWorkflowService) has a dependency to another service which get's started some time later. When i remove this @Reference dependency on the service, the service get's bound (exported/imported) as expected.
But i wasn't able to reproduce that in my little consumer/provider example setup yet.

Bye Peter

**Comment by scottslewis** [comment]
Hi Peter,

Yes please open a new issue.

Scott

**Comment by phermsdorf** [comment]
Hi @scottslewis ,

i finally managed to get my setup properly running via the tcpsocketdistributionprovider. The last problem i described finally was on my side.
I would like to get the missing pieces into the provider so we can finally use that and solve our long standing problem with "fixed hostnames".
Missing from my POV:
* custom Error handling on server side 
* custom Request Object to have additional information send with every request from the client

Both of these we had with the ecf generic provider by implementing custom HostContainerSelector, RegistrySharedObject.
I will create one issue and see how we can get going since both requirements seem to be doable if we could get the TCPSocketServerContainer implement ISharedObjectContainer. 
But i don't know if that's the was to go ...
Created #3

Thanks!
Bye Peter
